/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedCadastrosRouteImport } from './routes/_authenticated/cadastros'
import { Route as AuthenticatedCiclosRouteImport } from './routes/_authenticated/ciclos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedRegistroDiarioRouteImport } from './routes/_authenticated/registro-diario'

const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/_authenticated/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCadastrosRoute = AuthenticatedCadastrosRouteImport.update({
  id: '/_authenticated/cadastros',
  path: '/cadastros',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCiclosRoute = AuthenticatedCiclosRouteImport.update({
  id: '/_authenticated/ciclos',
  path: '/ciclos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/_authenticated/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRegistroDiarioRoute =
  AuthenticatedRegistroDiarioRouteImport.update({
    id: '/_authenticated/registro-diario',
    path: '/registro-diario',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/ciclos': typeof AuthenticatedCiclosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/registro-diario': typeof AuthenticatedRegistroDiarioRoute
}
export interface FileRoutesByTo {
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/ciclos': typeof AuthenticatedCiclosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/registro-diario': typeof AuthenticatedRegistroDiarioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/cadastros': typeof AuthenticatedCadastrosRoute
  '/_authenticated/ciclos': typeof AuthenticatedCiclosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/registro-diario': typeof AuthenticatedRegistroDiarioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auditoria'
    | '/cadastros'
    | '/ciclos'
    | '/dashboard'
    | '/kanban'
    | '/registro-diario'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auditoria'
    | '/cadastros'
    | '/ciclos'
    | '/dashboard'
    | '/kanban'
    | '/registro-diario'
  id:
    | '__root__'
    | '/_authenticated/auditoria'
    | '/_authenticated/cadastros'
    | '/_authenticated/ciclos'
    | '/_authenticated/dashboard'
    | '/_authenticated/kanban'
    | '/_authenticated/registro-diario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedCadastrosRoute: typeof AuthenticatedCadastrosRoute
  AuthenticatedCiclosRoute: typeof AuthenticatedCiclosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedRegistroDiarioRoute: typeof AuthenticatedRegistroDiarioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cadastros': {
      id: '/_authenticated/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AuthenticatedCadastrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ciclos': {
      id: '/_authenticated/ciclos'
      path: '/ciclos'
      fullPath: '/ciclos'
      preLoaderRoute: typeof AuthenticatedCiclosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/registro-diario': {
      id: '/_authenticated/registro-diario'
      path: '/registro-diario'
      fullPath: '/registro-diario'
      preLoaderRoute: typeof AuthenticatedRegistroDiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedCadastrosRoute: AuthenticatedCadastrosRoute,
  AuthenticatedCiclosRoute: AuthenticatedCiclosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedRegistroDiarioRoute: AuthenticatedRegistroDiarioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
